language: go
go:
- 1.11.x
env:
  global:
  - TF_ACC=1
  - secure: 2wlN2fKQCDZvQvXsqq7fQId8SnalADi/HqJr0/avtKz/mRdhSHMYME2rEeoq/Mhk2i57LQG2o18Fn/kzhPzJGs3jnJQ9IwhHK4ZZn5POJzGVP1OT5GQ0tYWKX4a49rYUE8BfcbqI9MaIvv/3ExAPUv/Mz//AJViVswbU6nI7Om7YCwiaxqyQnV3qa/zHSctA6WG6GMsz9sy0Lt56bqcJSTN6lNLS8sPVsxoxjAnN1lqMfflkNrpUU3520oI8I7igsjf2Tfl3pnaG+KgQs6/cUhhuYlGBGJnY2Dc4mciJBTfxXi8oGdFyjXRfAiXN+p9NlaEub8kKPxCaMl23vpPW7LxVeWp4L1oXuc4NkAnLWF8oD0aaYbLONgk1P4EuVIQm4zrlg8UxKLpf4Iv7jily3Q4/s4v0SMxKt2dBwVdKA7M+Jmn/Y45j5ONAPP12gAN61QfBsNvuU4Bcfrj6BsC64I1NUKGw4GMe9354NjEPpwVjWs7/vv1Tf3YsL7TanlmeofG1up/ezE5ORORCZHHB6oeCBWYCQdUYQEIq8Ypo2O9cw+dcmseyFo2L6CXKqJ4qXrF9dli6A3LRUI7A3GYJNAFvV9PT0RJ1XxepnVUPXFM55sT7sLYj128focEo6GofZIcC2Cc26H0GTnEkKyXb4n9yAIjiRkTz/bl+5eNTwaA=
script:
- make
after_success:
- make release
